---
- name: Create users with home dirs, emails and encrypt passwords
  hosts: dev_servers
  gather_facts: no
  become: yes
  vars_files:
    - vars/users
  tasks:
    - name: Create users with pass,email,homedir
      ansible.builtin.user:
        name: "{{ item.key }}"
        home: "{{ item.value.homedir }}"
        comment: "{{ item.value.comment }}"
        password: "{{ item.value.password }}"
      with_dict: 
        - "{{ users }}" 
