---
apache_enablerepo: ""

apache_listen_ip: "*"
apache_listen_port: 80
apache_listen_port_ssl: 443

role_path: "/root/ansible/ansible-epam/ansible-epam/task-03/roles/001_httpd/"

apache_create_vhosts: true
apache_vhosts_filename: "vhosts.conf"
apache_vhosts_template: "vhosts.conf.j2"


apache_global_vhost_settings: |
  DirectoryIndex index.php index.html

apache_vhosts:
  - servername: "node01.example.com"
    documentroot: "/var/www/html"

  - servername: "node02.example.com"
    documentroot: "/var/www/html"

apache_allow_override: "All"


apache_ignore_missing_ssl_certificate: true

apache_ssl_protocol: "All -SSLv2 -SSLv3"
apache_ssl_cipher_suite: "AES256+EECDH:AES256+EDH"

apache_mods_enabled:
  - rewrite.load
  - ssl.load
apache_mods_disabled: []

apache_state: started

apache_enabled: yes

apache_restart_state: restarted

apache_packages_state: latest
